const EMPLOYEE_ROLES = ['RECEPTIONIST', 'DOCTOR', 'PHARMACIST', 'ACCOUNTANT', 'ADMIN'];
const APPOINTMENT_STATUSES = ['SCHEDULED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED'];
const BILLING_STATUSES = ['DRAFT', 'PAID', 'PARTIALLY_PAID'];
const PAYMENT_MODES = ['CASH', 'INSURANCE', 'NHIF', 'MPESA'];
const LAB_ORDER_STATUSES = ['PENDING', 'COMPLETED'];
const NOTIFICATION_CHANNELS = ['IN_APP', 'SMS', 'EMAIL'];
const AUDIT_ACTIONS = ['CREATE', 'UPDATE', 'DELETE', 'VIEW', 'LOGIN', 'LOGOUT'];

module.exports = {
  EMPLOYEE_ROLES,
  APPOINTMENT_STATUSES,
  BILLING_STATUSES,
  PAYMENT_MODES,
  LAB_ORDER_STATUSES,
  NOTIFICATION_CHANNELS,
  AUDIT_ACTIONS
};
